import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import FloatingCircles from "./components/FloatingCircles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Francesco Gragnaniello Portfolio",
  description: "Generated by Francesco Gragnaniello",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setThemeScript = `(()=>{try{const t=localStorage.getItem('theme');if(t==='dark'){document.documentElement.classList.add('dark');}else if(t==='light'){document.documentElement.classList.remove('dark');}else if(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches){document.documentElement.classList.add('dark');} }catch(e){} })();`;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-zinc-50 to-white dark:from-black dark:to-zinc-900 theme-transition`}
      >
        <script dangerouslySetInnerHTML={{ __html: setThemeScript }} />
        <FloatingCircles />
        <Navbar />

        <main className="pt-28 md:pt-32">{children}</main>
      </body>
    </html>
  );
}
